Fix typos on README
Rocketseat/react-native-template-rocketseat-basic pull request #5
Opened 2019-06-02 04:52 UTC by lucianomlima

2019-06-02 16:08 UTC, jpdemagalhaes requested changes

2019-06-02 16:08 UTC, jpdemagalhaes commented on README.md
> +- [Reactotron](https://github.com/infinitered/reactotron) - O Reactotron é um app Desktop para inspecionar projetos em React ou React Native. Está disponível para MacOS, Linux e Windows;
Aqui estava certo já antes do commit, a Apple decidiu chamar de macOS mesmo.

2019-06-03 00:07 UTC, lucianomlima commented on README.md
> +- [Reactotron](https://github.com/infinitered/reactotron) - O Reactotron é um app Desktop para inspecionar projetos em React ou React Native. Está disponível para MacOS, Linux e Windows;
Fixed

2019-06-03 01:45 UTC, cssorlandi approved these changes

2019-06-03 01:46 UTC, csorlandi commented
Opa @lucianomlima obrigado pela contribuição 😉 

Você pegou detalhes bem pontuais rsrs

2019-06-03 03:45 UTC, jpdemagalhaes approved these changes

2019-06-03 03:46 UTC, merged